import numpy as np

import torch
from torchvision.models import resnet50

import timm

# from resnet50_vd import resnet50_vd
import paddle
from PaddleClas.ppcls.modeling.architectures.resnet_vd import ResNet50_vd
from pd2onnx import export_model_to_ONNX


keys_map = {
    'conv1.0.weight': 'conv1_1._conv.weight', 
    'conv1.1.weight': 'conv1_1._batch_norm.weight', 
    'conv1.1.bias': 'conv1_1._batch_norm.bias', 
    'conv1.1.running_mean': 'conv1_1._batch_norm._mean', 
    'conv1.1.running_var': 'conv1_1._batch_norm._variance', 
    # 'conv1.1.num_batches_tracked', 
    'conv1.3.weight': 'conv1_2._conv.weight', 
    'conv1.4.weight': 'conv1_2._batch_norm.weight', 
    'conv1.4.bias': 'conv1_2._batch_norm.bias', 
    'conv1.4.running_mean': 'conv1_2._batch_norm._mean', 
    'conv1.4.running_var': 'conv1_2._batch_norm._variance', 
    # 'conv1.4.num_batches_tracked', 
    'conv1.6.weight': 'conv1_3._conv.weight', 
    'bn1.weight': 'conv1_3._batch_norm.weight', 
    'bn1.bias': 'conv1_3._batch_norm.bias', 
    'bn1.running_mean': 'conv1_3._batch_norm._mean', 
    'bn1.running_var': 'conv1_3._batch_norm._variance', 
    # 'bn1.num_batches_tracked', 

    'layer1.0.conv1.weight': 'bb_0_0.conv0._conv.weight', 
    'layer1.0.bn1.weight': 'bb_0_0.conv0._batch_norm.weight', 
    'layer1.0.bn1.bias': 'bb_0_0.conv0._batch_norm.bias', 
    'layer1.0.bn1.running_mean': 'bb_0_0.conv0._batch_norm._mean', 
    'layer1.0.bn1.running_var': 'bb_0_0.conv0._batch_norm._variance', 
    # 'layer1.0.bn1.num_batches_tracked', 
    'layer1.0.conv2.weight': 'bb_0_0.conv1._conv.weight',
    'layer1.0.bn2.weight': 'bb_0_0.conv1._batch_norm.weight', 
    'layer1.0.bn2.bias': 'bb_0_0.conv1._batch_norm.bias', 
    'layer1.0.bn2.running_mean': 'bb_0_0.conv1._batch_norm._mean', 
    'layer1.0.bn2.running_var': 'bb_0_0.conv1._batch_norm._variance', 
    # 'layer1.0.bn2.num_batches_tracked', 
    'layer1.0.conv3.weight': 'bb_0_0.conv2._conv.weight', 
    'layer1.0.bn3.weight': 'bb_0_0.conv2._batch_norm.weight', 
    'layer1.0.bn3.bias': 'bb_0_0.conv2._batch_norm.bias', 
    'layer1.0.bn3.running_mean': 'bb_0_0.conv2._batch_norm._mean', 
    'layer1.0.bn3.running_var': 'bb_0_0.conv2._batch_norm._variance', 
    # 'layer1.0.bn3.num_batches_tracked', 
    'layer1.0.downsample.1.weight': 'bb_0_0.short._conv.weight', 
    'layer1.0.downsample.2.weight': 'bb_0_0.short._batch_norm.weight', 
    'layer1.0.downsample.2.bias': 'bb_0_0.short._batch_norm.bias', 
    'layer1.0.downsample.2.running_mean': 'bb_0_0.short._batch_norm._mean', 
    'layer1.0.downsample.2.running_var': 'bb_0_0.short._batch_norm._variance', 
    # 'layer1.0.downsample.2.num_batches_tracked', 
    'layer1.1.conv1.weight': 'bb_0_1.conv0._conv.weight', 
    'layer1.1.bn1.weight': 'bb_0_1.conv0._batch_norm.weight', 
    'layer1.1.bn1.bias': 'bb_0_1.conv0._batch_norm.bias', 
    'layer1.1.bn1.running_mean': 'bb_0_1.conv0._batch_norm._mean', 
    'layer1.1.bn1.running_var': 'bb_0_1.conv0._batch_norm._variance', 
    # 'layer1.1.bn1.num_batches_tracked', 
    'layer1.1.conv2.weight': 'bb_0_1.conv1._conv.weight', 
    'layer1.1.bn2.weight': 'bb_0_1.conv1._batch_norm.weight', 
    'layer1.1.bn2.bias': 'bb_0_1.conv1._batch_norm.bias', 
    'layer1.1.bn2.running_mean': 'bb_0_1.conv1._batch_norm._mean', 
    'layer1.1.bn2.running_var': 'bb_0_1.conv1._batch_norm._variance', 
    # 'layer1.1.bn2.num_batches_tracked', 
    'layer1.1.conv3.weight': 'bb_0_1.conv2._conv.weight', 
    'layer1.1.bn3.weight': 'bb_0_1.conv2._batch_norm.weight', 
    'layer1.1.bn3.bias': 'bb_0_1.conv2._batch_norm.bias', 
    'layer1.1.bn3.running_mean': 'bb_0_1.conv2._batch_norm._mean', 
    'layer1.1.bn3.running_var': 'bb_0_1.conv2._batch_norm._variance', 
    # 'layer1.1.bn3.num_batches_tracked', 
    'layer1.2.conv1.weight': 'bb_0_2.conv0._conv.weight', 
    'layer1.2.bn1.weight': 'bb_0_2.conv0._batch_norm.weight', 
    'layer1.2.bn1.bias': 'bb_0_2.conv0._batch_norm.bias', 
    'layer1.2.bn1.running_mean': 'bb_0_2.conv0._batch_norm._mean', 
    'layer1.2.bn1.running_var': 'bb_0_2.conv0._batch_norm._variance', 
    # 'layer1.2.bn1.num_batches_tracked', 
    'layer1.2.conv2.weight': 'bb_0_2.conv1._conv.weight', 
    'layer1.2.bn2.weight': 'bb_0_2.conv1._batch_norm.weight', 
    'layer1.2.bn2.bias': 'bb_0_2.conv1._batch_norm.bias', 
    'layer1.2.bn2.running_mean': 'bb_0_2.conv1._batch_norm._mean', 
    'layer1.2.bn2.running_var': 'bb_0_2.conv1._batch_norm._variance', 
    # 'layer1.2.bn2.num_batches_tracked', 
    'layer1.2.conv3.weight': 'bb_0_2.conv2._conv.weight', 
    'layer1.2.bn3.weight': 'bb_0_2.conv2._batch_norm.weight', 
    'layer1.2.bn3.bias': 'bb_0_2.conv2._batch_norm.bias', 
    'layer1.2.bn3.running_mean': 'bb_0_2.conv2._batch_norm._mean', 
    'layer1.2.bn3.running_var': 'bb_0_2.conv2._batch_norm._variance', 
    # 'layer1.2.bn3.num_batches_tracked', 

    'layer2.0.conv1.weight': 'bb_1_0.conv0._conv.weight', 
    'layer2.0.bn1.weight': 'bb_1_0.conv0._batch_norm.weight', 
    'layer2.0.bn1.bias': 'bb_1_0.conv0._batch_norm.bias', 
    'layer2.0.bn1.running_mean': 'bb_1_0.conv0._batch_norm._mean', 
    'layer2.0.bn1.running_var': 'bb_1_0.conv0._batch_norm._variance', 
    # 'layer2.0.bn1.num_batches_tracked', 
    'layer2.0.conv2.weight': 'bb_1_0.conv1._conv.weight', 
    'layer2.0.bn2.weight': 'bb_1_0.conv1._batch_norm.weight', 
    'layer2.0.bn2.bias': 'bb_1_0.conv1._batch_norm.bias', 
    'layer2.0.bn2.running_mean': 'bb_1_0.conv1._batch_norm._mean', 
    'layer2.0.bn2.running_var': 'bb_1_0.conv1._batch_norm._variance', 
    # 'layer2.0.bn2.num_batches_tracked', 
    'layer2.0.conv3.weight': 'bb_1_0.conv2._conv.weight', 
    'layer2.0.bn3.weight': 'bb_1_0.conv2._batch_norm.weight', 
    'layer2.0.bn3.bias': 'bb_1_0.conv2._batch_norm.bias', 
    'layer2.0.bn3.running_mean': 'bb_1_0.conv2._batch_norm._mean', 
    'layer2.0.bn3.running_var': 'bb_1_0.conv2._batch_norm._variance', 
    # 'layer2.0.bn3.num_batches_tracked', 
    'layer2.0.downsample.1.weight': 'bb_1_0.short._conv.weight', 
    'layer2.0.downsample.2.weight': 'bb_1_0.short._batch_norm.weight', 
    'layer2.0.downsample.2.bias': 'bb_1_0.short._batch_norm.bias', 
    'layer2.0.downsample.2.running_mean': 'bb_1_0.short._batch_norm._mean', 
    'layer2.0.downsample.2.running_var': 'bb_1_0.short._batch_norm._variance', 
    # 'layer2.0.downsample.2.num_batches_tracked', 
    'layer2.1.conv1.weight': 'bb_1_1.conv0._conv.weight', 
    'layer2.1.bn1.weight': 'bb_1_1.conv0._batch_norm.weight', 
    'layer2.1.bn1.bias': 'bb_1_1.conv0._batch_norm.bias', 
    'layer2.1.bn1.running_mean': 'bb_1_1.conv0._batch_norm._mean', 
    'layer2.1.bn1.running_var': 'bb_1_1.conv0._batch_norm._variance', 
    # 'layer2.1.bn1.num_batches_tracked', 
    'layer2.1.conv2.weight': 'bb_1_1.conv1._conv.weight', 
    'layer2.1.bn2.weight': 'bb_1_1.conv1._batch_norm.weight', 
    'layer2.1.bn2.bias': 'bb_1_1.conv1._batch_norm.bias', 
    'layer2.1.bn2.running_mean': 'bb_1_1.conv1._batch_norm._mean', 
    'layer2.1.bn2.running_var': 'bb_1_1.conv1._batch_norm._variance', 
    # 'layer2.1.bn2.num_batches_tracked', 
    'layer2.1.conv3.weight': 'bb_1_1.conv2._conv.weight', 
    'layer2.1.bn3.weight': 'bb_1_1.conv2._batch_norm.weight', 
    'layer2.1.bn3.bias': 'bb_1_1.conv2._batch_norm.bias', 
    'layer2.1.bn3.running_mean': 'bb_1_1.conv2._batch_norm._mean', 
    'layer2.1.bn3.running_var': 'bb_1_1.conv2._batch_norm._variance', 
    # 'layer2.1.bn3.num_batches_tracked', 
    'layer2.2.conv1.weight': 'bb_1_2.conv0._conv.weight', 
    'layer2.2.bn1.weight': 'bb_1_2.conv0._batch_norm.weight', 
    'layer2.2.bn1.bias': 'bb_1_2.conv0._batch_norm.bias', 
    'layer2.2.bn1.running_mean': 'bb_1_2.conv0._batch_norm._mean', 
    'layer2.2.bn1.running_var': 'bb_1_2.conv0._batch_norm._variance', 
    # 'layer2.2.bn1.num_batches_tracked', 
    'layer2.2.conv2.weight': 'bb_1_2.conv1._conv.weight', 
    'layer2.2.bn2.weight': 'bb_1_2.conv1._batch_norm.weight', 
    'layer2.2.bn2.bias': 'bb_1_2.conv1._batch_norm.bias', 
    'layer2.2.bn2.running_mean': 'bb_1_2.conv1._batch_norm._mean', 
    'layer2.2.bn2.running_var': 'bb_1_2.conv1._batch_norm._variance', 
    # 'layer2.2.bn2.num_batches_tracked', 
    'layer2.2.conv3.weight': 'bb_1_2.conv2._conv.weight', 
    'layer2.2.bn3.weight': 'bb_1_2.conv2._batch_norm.weight', 
    'layer2.2.bn3.bias': 'bb_1_2.conv2._batch_norm.bias', 
    'layer2.2.bn3.running_mean': 'bb_1_2.conv2._batch_norm._mean', 
    'layer2.2.bn3.running_var': 'bb_1_2.conv2._batch_norm._variance', 
    # 'layer2.2.bn3.num_batches_tracked', 
    'layer2.3.conv1.weight': 'bb_1_3.conv0._conv.weight', 
    'layer2.3.bn1.weight': 'bb_1_3.conv0._batch_norm.weight', 
    'layer2.3.bn1.bias': 'bb_1_3.conv0._batch_norm.bias', 
    'layer2.3.bn1.running_mean': 'bb_1_3.conv0._batch_norm._mean', 
    'layer2.3.bn1.running_var': 'bb_1_3.conv0._batch_norm._variance', 
    # 'layer2.3.bn1.num_batches_tracked', 
    'layer2.3.conv2.weight': 'bb_1_3.conv1._conv.weight', 
    'layer2.3.bn2.weight': 'bb_1_3.conv1._batch_norm.weight', 
    'layer2.3.bn2.bias': 'bb_1_3.conv1._batch_norm.bias', 
    'layer2.3.bn2.running_mean': 'bb_1_3.conv1._batch_norm._mean', 
    'layer2.3.bn2.running_var': 'bb_1_3.conv1._batch_norm._variance', 
    # 'layer2.3.bn2.num_batches_tracked', 
    'layer2.3.conv3.weight': 'bb_1_3.conv2._conv.weight', 
    'layer2.3.bn3.weight': 'bb_1_3.conv2._batch_norm.weight', 
    'layer2.3.bn3.bias': 'bb_1_3.conv2._batch_norm.bias', 
    'layer2.3.bn3.running_mean': 'bb_1_3.conv2._batch_norm._mean', 
    'layer2.3.bn3.running_var': 'bb_1_3.conv2._batch_norm._variance', 
    # 'layer2.3.bn3.num_batches_tracked', 

    'layer3.0.conv1.weight': 'bb_2_0.conv0._conv.weight', 
    'layer3.0.bn1.weight': 'bb_2_0.conv0._batch_norm.weight', 
    'layer3.0.bn1.bias': 'bb_2_0.conv0._batch_norm.bias', 
    'layer3.0.bn1.running_mean': 'bb_2_0.conv0._batch_norm._mean', 
    'layer3.0.bn1.running_var': 'bb_2_0.conv0._batch_norm._variance', 
    # 'layer3.0.bn1.num_batches_tracked', 
    'layer3.0.conv2.weight': 'bb_2_0.conv1._conv.weight', 
    'layer3.0.bn2.weight': 'bb_2_0.conv1._batch_norm.weight', 
    'layer3.0.bn2.bias': 'bb_2_0.conv1._batch_norm.bias', 
    'layer3.0.bn2.running_mean': 'bb_2_0.conv1._batch_norm._mean', 
    'layer3.0.bn2.running_var': 'bb_2_0.conv1._batch_norm._variance', 
    # 'layer3.0.bn2.num_batches_tracked', 
    'layer3.0.conv3.weight': 'bb_2_0.conv2._conv.weight', 
    'layer3.0.bn3.weight': 'bb_2_0.conv2._batch_norm.weight', 
    'layer3.0.bn3.bias': 'bb_2_0.conv2._batch_norm.bias', 
    'layer3.0.bn3.running_mean': 'bb_2_0.conv2._batch_norm._mean', 
    'layer3.0.bn3.running_var': 'bb_2_0.conv2._batch_norm._variance', 
    # 'layer3.0.bn3.num_batches_tracked', 
    'layer3.0.downsample.1.weight': 'bb_2_0.short._conv.weight', 
    'layer3.0.downsample.2.weight': 'bb_2_0.short._batch_norm.weight', 
    'layer3.0.downsample.2.bias': 'bb_2_0.short._batch_norm.bias', 
    'layer3.0.downsample.2.running_mean': 'bb_2_0.short._batch_norm._mean', 
    'layer3.0.downsample.2.running_var': 'bb_2_0.short._batch_norm._variance', 
    # 'layer3.0.downsample.2.num_batches_tracked', 
    'layer3.1.conv1.weight': 'bb_2_1.conv0._conv.weight', 
    'layer3.1.bn1.weight': 'bb_2_1.conv0._batch_norm.weight', 
    'layer3.1.bn1.bias': 'bb_2_1.conv0._batch_norm.bias', 
    'layer3.1.bn1.running_mean': 'bb_2_1.conv0._batch_norm._mean', 
    'layer3.1.bn1.running_var': 'bb_2_1.conv0._batch_norm._variance', 
    # 'layer3.1.bn1.num_batches_tracked', 
    'layer3.1.conv2.weight': 'bb_2_1.conv1._conv.weight', 
    'layer3.1.bn2.weight': 'bb_2_1.conv1._batch_norm.weight', 
    'layer3.1.bn2.bias': 'bb_2_1.conv1._batch_norm.bias', 
    'layer3.1.bn2.running_mean': 'bb_2_1.conv1._batch_norm._mean', 
    'layer3.1.bn2.running_var': 'bb_2_1.conv1._batch_norm._variance', 
    # 'layer3.1.bn2.num_batches_tracked', 
    'layer3.1.conv3.weight': 'bb_2_1.conv2._conv.weight', 
    'layer3.1.bn3.weight': 'bb_2_1.conv2._batch_norm.weight', 
    'layer3.1.bn3.bias': 'bb_2_1.conv2._batch_norm.bias', 
    'layer3.1.bn3.running_mean': 'bb_2_1.conv2._batch_norm._mean', 
    'layer3.1.bn3.running_var': 'bb_2_1.conv2._batch_norm._variance', 
    # 'layer3.1.bn3.num_batches_tracked', 
    'layer3.2.conv1.weight': 'bb_2_2.conv0._conv.weight', 
    'layer3.2.bn1.weight': 'bb_2_2.conv0._batch_norm.weight', 
    'layer3.2.bn1.bias': 'bb_2_2.conv0._batch_norm.bias', 
    'layer3.2.bn1.running_mean': 'bb_2_2.conv0._batch_norm._mean', 
    'layer3.2.bn1.running_var': 'bb_2_2.conv0._batch_norm._variance', 
    # 'layer3.2.bn1.num_batches_tracked', 
    'layer3.2.conv2.weight': 'bb_2_2.conv1._conv.weight', 
    'layer3.2.bn2.weight': 'bb_2_2.conv1._batch_norm.weight', 
    'layer3.2.bn2.bias': 'bb_2_2.conv1._batch_norm.bias', 
    'layer3.2.bn2.running_mean': 'bb_2_2.conv1._batch_norm._mean', 
    'layer3.2.bn2.running_var': 'bb_2_2.conv1._batch_norm._variance', 
    # 'layer3.2.bn2.num_batches_tracked', 
    'layer3.2.conv3.weight': 'bb_2_2.conv2._conv.weight', 
    'layer3.2.bn3.weight': 'bb_2_2.conv2._batch_norm.weight', 
    'layer3.2.bn3.bias': 'bb_2_2.conv2._batch_norm.bias', 
    'layer3.2.bn3.running_mean': 'bb_2_2.conv2._batch_norm._mean', 
    'layer3.2.bn3.running_var': 'bb_2_2.conv2._batch_norm._variance', 
    # 'layer3.2.bn3.num_batches_tracked', 
    'layer3.3.conv1.weight': 'bb_2_3.conv0._conv.weight', 
    'layer3.3.bn1.weight': 'bb_2_3.conv0._batch_norm.weight', 
    'layer3.3.bn1.bias': 'bb_2_3.conv0._batch_norm.bias', 
    'layer3.3.bn1.running_mean': 'bb_2_3.conv0._batch_norm._mean', 
    'layer3.3.bn1.running_var': 'bb_2_3.conv0._batch_norm._variance', 
    # 'layer3.3.bn1.num_batches_tracked', 
    'layer3.3.conv2.weight': 'bb_2_3.conv1._conv.weight', 
    'layer3.3.bn2.weight': 'bb_2_3.conv1._batch_norm.weight', 
    'layer3.3.bn2.bias': 'bb_2_3.conv1._batch_norm.bias', 
    'layer3.3.bn2.running_mean': 'bb_2_3.conv1._batch_norm._mean', 
    'layer3.3.bn2.running_var': 'bb_2_3.conv1._batch_norm._variance', 
    # 'layer3.3.bn2.num_batches_tracked', 
    'layer3.3.conv3.weight': 'bb_2_3.conv2._conv.weight', 
    'layer3.3.bn3.weight': 'bb_2_3.conv2._batch_norm.weight', 
    'layer3.3.bn3.bias': 'bb_2_3.conv2._batch_norm.bias', 
    'layer3.3.bn3.running_mean': 'bb_2_3.conv2._batch_norm._mean', 
    'layer3.3.bn3.running_var': 'bb_2_3.conv2._batch_norm._variance', 
    # 'layer3.3.bn3.num_batches_tracked', 
    'layer3.4.conv1.weight': 'bb_2_4.conv0._conv.weight', 
    'layer3.4.bn1.weight': 'bb_2_4.conv0._batch_norm.weight', 
    'layer3.4.bn1.bias': 'bb_2_4.conv0._batch_norm.bias', 
    'layer3.4.bn1.running_mean': 'bb_2_4.conv0._batch_norm._mean', 
    'layer3.4.bn1.running_var': 'bb_2_4.conv0._batch_norm._variance', 
    # 'layer3.4.bn1.num_batches_tracked', 
    'layer3.4.conv2.weight': 'bb_2_4.conv1._conv.weight', 
    'layer3.4.bn2.weight': 'bb_2_4.conv1._batch_norm.weight', 
    'layer3.4.bn2.bias': 'bb_2_4.conv1._batch_norm.bias', 
    'layer3.4.bn2.running_mean': 'bb_2_4.conv1._batch_norm._mean', 
    'layer3.4.bn2.running_var': 'bb_2_4.conv1._batch_norm._variance', 
    # 'layer3.4.bn2.num_batches_tracked', 
    'layer3.4.conv3.weight': 'bb_2_4.conv2._conv.weight', 
    'layer3.4.bn3.weight': 'bb_2_4.conv2._batch_norm.weight', 
    'layer3.4.bn3.bias': 'bb_2_4.conv2._batch_norm.bias', 
    'layer3.4.bn3.running_mean': 'bb_2_4.conv2._batch_norm._mean', 
    'layer3.4.bn3.running_var': 'bb_2_4.conv2._batch_norm._variance', 
    # 'layer3.4.bn3.num_batches_tracked', 
    'layer3.5.conv1.weight': 'bb_2_5.conv0._conv.weight', 
    'layer3.5.bn1.weight': 'bb_2_5.conv0._batch_norm.weight', 
    'layer3.5.bn1.bias': 'bb_2_5.conv0._batch_norm.bias', 
    'layer3.5.bn1.running_mean': 'bb_2_5.conv0._batch_norm._mean', 
    'layer3.5.bn1.running_var': 'bb_2_5.conv0._batch_norm._variance', 
    # 'layer3.5.bn1.num_batches_tracked', 
    'layer3.5.conv2.weight': 'bb_2_5.conv1._conv.weight', 
    'layer3.5.bn2.weight': 'bb_2_5.conv1._batch_norm.weight', 
    'layer3.5.bn2.bias': 'bb_2_5.conv1._batch_norm.bias', 
    'layer3.5.bn2.running_mean': 'bb_2_5.conv1._batch_norm._mean', 
    'layer3.5.bn2.running_var': 'bb_2_5.conv1._batch_norm._variance', 
    # 'layer3.5.bn2.num_batches_tracked', 
    'layer3.5.conv3.weight': 'bb_2_5.conv2._conv.weight', 
    'layer3.5.bn3.weight': 'bb_2_5.conv2._batch_norm.weight', 
    'layer3.5.bn3.bias': 'bb_2_5.conv2._batch_norm.bias', 
    'layer3.5.bn3.running_mean': 'bb_2_5.conv2._batch_norm._mean', 
    'layer3.5.bn3.running_var': 'bb_2_5.conv2._batch_norm._variance', 
    # 'layer3.5.bn3.num_batches_tracked', 

    'layer4.0.conv1.weight': 'bb_3_0.conv0._conv.weight', 
    'layer4.0.bn1.weight': 'bb_3_0.conv0._batch_norm.weight', 
    'layer4.0.bn1.bias': 'bb_3_0.conv0._batch_norm.bias', 
    'layer4.0.bn1.running_mean': 'bb_3_0.conv0._batch_norm._mean', 
    'layer4.0.bn1.running_var': 'bb_3_0.conv0._batch_norm._variance', 
    # 'layer4.0.bn1.num_batches_tracked', 
    'layer4.0.conv2.weight': 'bb_3_0.conv1._conv.weight', 
    'layer4.0.bn2.weight': 'bb_3_0.conv1._batch_norm.weight', 
    'layer4.0.bn2.bias': 'bb_3_0.conv1._batch_norm.bias', 
    'layer4.0.bn2.running_mean': 'bb_3_0.conv1._batch_norm._mean', 
    'layer4.0.bn2.running_var': 'bb_3_0.conv1._batch_norm._variance', 
    # 'layer4.0.bn2.num_batches_tracked', 
    'layer4.0.conv3.weight': 'bb_3_0.conv2._conv.weight', 
    'layer4.0.bn3.weight': 'bb_3_0.conv2._batch_norm.weight', 
    'layer4.0.bn3.bias': 'bb_3_0.conv2._batch_norm.bias', 
    'layer4.0.bn3.running_mean': 'bb_3_0.conv2._batch_norm._mean', 
    'layer4.0.bn3.running_var': 'bb_3_0.conv2._batch_norm._variance', 
    # 'layer4.0.bn3.num_batches_tracked', 
    'layer4.0.downsample.1.weight': 'bb_3_0.short._conv.weight', 
    'layer4.0.downsample.2.weight': 'bb_3_0.short._batch_norm.weight', 
    'layer4.0.downsample.2.bias': 'bb_3_0.short._batch_norm.bias', 
    'layer4.0.downsample.2.running_mean': 'bb_3_0.short._batch_norm._mean', 
    'layer4.0.downsample.2.running_var': 'bb_3_0.short._batch_norm._variance', 
    # 'layer4.0.downsample.2.num_batches_tracked', 
    'layer4.1.conv1.weight': 'bb_3_1.conv0._conv.weight', 
    'layer4.1.bn1.weight': 'bb_3_1.conv0._batch_norm.weight', 
    'layer4.1.bn1.bias': 'bb_3_1.conv0._batch_norm.bias', 
    'layer4.1.bn1.running_mean': 'bb_3_1.conv0._batch_norm._mean', 
    'layer4.1.bn1.running_var': 'bb_3_1.conv0._batch_norm._variance', 
    # 'layer4.1.bn1.num_batches_tracked', 
    'layer4.1.conv2.weight': 'bb_3_1.conv1._conv.weight', 
    'layer4.1.bn2.weight': 'bb_3_1.conv1._batch_norm.weight', 
    'layer4.1.bn2.bias': 'bb_3_1.conv1._batch_norm.bias', 
    'layer4.1.bn2.running_mean': 'bb_3_1.conv1._batch_norm._mean', 
    'layer4.1.bn2.running_var': 'bb_3_1.conv1._batch_norm._variance', 
    # 'layer4.1.bn2.num_batches_tracked', 
    'layer4.1.conv3.weight': 'bb_3_1.conv2._conv.weight', 
    'layer4.1.bn3.weight': 'bb_3_1.conv2._batch_norm.weight', 
    'layer4.1.bn3.bias': 'bb_3_1.conv2._batch_norm.bias', 
    'layer4.1.bn3.running_mean': 'bb_3_1.conv2._batch_norm._mean', 
    'layer4.1.bn3.running_var': 'bb_3_1.conv2._batch_norm._variance', 
    # 'layer4.1.bn3.num_batches_tracked', 
    'layer4.2.conv1.weight': 'bb_3_2.conv0._conv.weight', 
    'layer4.2.bn1.weight': 'bb_3_2.conv0._batch_norm.weight', 
    'layer4.2.bn1.bias': 'bb_3_2.conv0._batch_norm.bias', 
    'layer4.2.bn1.running_mean': 'bb_3_2.conv0._batch_norm._mean', 
    'layer4.2.bn1.running_var': 'bb_3_2.conv0._batch_norm._variance', 
    # 'layer4.2.bn1.num_batches_tracked', 
    'layer4.2.conv2.weight': 'bb_3_2.conv1._conv.weight', 
    'layer4.2.bn2.weight': 'bb_3_2.conv1._batch_norm.weight', 
    'layer4.2.bn2.bias': 'bb_3_2.conv1._batch_norm.bias', 
    'layer4.2.bn2.running_mean': 'bb_3_2.conv1._batch_norm._mean', 
    'layer4.2.bn2.running_var': 'bb_3_2.conv1._batch_norm._variance', 
    # 'layer4.2.bn2.num_batches_tracked', 
    'layer4.2.conv3.weight': 'bb_3_2.conv2._conv.weight', 
    'layer4.2.bn3.weight': 'bb_3_2.conv2._batch_norm.weight', 
    'layer4.2.bn3.bias': 'bb_3_2.conv2._batch_norm.bias', 
    'layer4.2.bn3.running_mean': 'bb_3_2.conv2._batch_norm._mean', 
    'layer4.2.bn3.running_var': 'bb_3_2.conv2._batch_norm._variance', 
    # 'layer4.2.bn3.num_batches_tracked', 
    # 'fc.weight', 
    # 'fc.bias',
}


def main():
    pd_model = ResNet50_vd()
    pretrain_path = '/root/paddle/models/ResNet50_vd_10w_pretrained.pdparams'
    state_dict = paddle.load(pretrain_path)
    # pd_model.load_dict(state_dict)
    # pd_model.eval()

    x = np.random.random((2, 3, 224, 224)).astype('float32')

    timm_state_dict = torch.load('models/resnet50d_ra2-464e36ba.pth')
    for torch_key in keys_map:
        # print(f'{torch_key} -> {keys_map[torch_key]}: {} -> {}')
        # import ipdb; ipdb.set_trace()
        assert timm_state_dict[torch_key].shape == torch.Tensor(state_dict[keys_map[torch_key]]).shape
        timm_state_dict[torch_key] = torch.Tensor(state_dict[keys_map[torch_key]])
    model = timm.create_model('resnet50d')
    model.load_state_dict(timm_state_dict)
    # import ipdb; ipdb.set_trace()
    

    
    print("?")


if __name__ == '__main__':
    main()
